version: 0.2

phases:
  pre_build:
    commands:
      - echo "🔍 AWS CLI Version:"
      - aws --version
      - echo "🐳 Docker Version:"
      - docker --version
      - echo "🔐 Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 699475953949.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=699475953949.dkr.ecr.ap-south-1.amazonaws.com/sample-java-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo "🔨 Building the application..."
      - mvn clean package
      - echo "📁 Files in current directory:"
      - ls -al
      - echo "🐳 Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo "✅ Docker build completed"
      - docker images  # show available images to verify it was built

  post_build:
    commands:
      - echo "📤 Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "📝 Creating imagedefinitions.json..."
      - printf '[{"name":"sample-java-app","imageUri":"%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

